### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by Zumbalamambo** [ztipnis/Unity-ZBar-Wrapper#1]
How do I  build it? please add wiki

**Comment by kjyv** [comment]
Using the build.sh does not work, using cmake results in libzbar.a (for macOS?) and an error when building the wrapper.
Can this be used for Unity Android builds? If so, yes, some build and integration in Unity instructions would be very helpful

**Comment by ztipnis** [comment]
I don't have time to work on this, and so have marked this abandoned. If anyone wants to pick this up, its pretty straightforward, but theres no use adding a wiki in the meantime since it doesn't even work.
